kind: ServiceAccount
apiVersion: v1
metadata:
  name: pipeline
imagePullSecrets:
  - name: {{ include "parasol-store-build.name" . }}-registry-creds
secrets:
  - name: {{ include "parasol-store-build.name" . }}-registry-creds
