apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: {{ include "parasol-store-build.name" . }}-pr-merged
spec:
  params:
    - name: git-repo-url
      value: $(body.object_attributes.source.git_http_url)
    - name: git-revision
      value: $(body.object_attributes.merge_commit_sha)
    - name: git-revision-short
      value: $(extensions.commit-id-short)
    - name: output-image
      value: {{ include "parasol-store.image" . }}
    - name: dockerfile
      value: {{ .Values.image.dockerfile }}
